### ISSUE TITLE
_BSD_SOURCE deprecated

### ISSUE THREAD

**Issue by kisvegabor** [littlevgl/pc_simulator_sdl_eclipse#38]
@embeddedt 
I saw that you added `_BSD_SOURCE` in 2bb03e78 but I got a wrning for it:

```
#warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Wcpp]
```
Should we update it?

**Comment by embeddedt** [comment]
@kisvegabor I'll fix that. Strangely my documentation didn't mention that `_DEFAULT_SOURCE` even existed or that `_BSD_SOURCE` is deprecated...

**Comment by embeddedt** [comment]
Fixed in https://github.com/littlevgl/pc_simulator_sdl_eclipse/commit/4e3ef8ebacbd721d366bbd992fd5e9eafd92cd94.

**Comment by kisvegabor** [comment]
Thank you!
