### ISSUE TITLE
docker run lvgl_simulator block

### ISSUE THREAD

**Issue by JianwenLi-GS** [littlevgl/pc_simulator_sdl_eclipse#41]
sudo docker run lvgl_simulator   **//block here until press CTRL+C**

^Cused:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624
used:  10824 ( 17 %), frag:   1 %, biggest free:  54624

**Comment by embeddedt** [comment]
What's the problem here?

**Comment by JianwenLi-GS** [comment]
How to use  lvgl_simulator docker? No output or graphical menu appears after running “sudo docker run lvgl_simulator ”

**Comment by kisvegabor** [comment]
@BrianPugh, can you have a look at it? (The Dockerfile was added by Brian)

**Comment by JianwenLi-GS** [comment]
> How to use lvgl_simulator docker? No output or graphical menu appears after running “sudo docker run lvgl_simulator ”

My PC‘s system is Ubuntu 18.04

**Comment by BrianPugh** [comment]
see #42 . However, none of the Dockerfile changes actually impacts you (except maybe the instructions). This is a general Docker X11 forwarding issue. I added some brief instructions on how to (unsafely) X11 forward from a Docker container to your desktop environment. For more information, search "Docker X11 forwarding"
