### ISSUE TITLE
lv_drivers @ 39fe864 404 not found

### ISSUE THREAD

**Issue by staunchheart** [littlevgl/pc_simulator_sdl_eclipse#46]
lv_drivers @ 39fe864 404 not found

or download it as zip here. 
but https://codeload.github.com/littlevgl/pc_simulator_sdl_eclipse/zip/dev-6.0 404 not found

**Comment by kisvegabor** [comment]
I've fixed it.

I don't know codeload, but you should use the `master` branch because dev-6.0 was deleted after the release.

**Comment by embeddedt** [comment]
> I don't know codeload

I assume that is the server handling "Download ZIP" requests.
